name: bandon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_html: ^1.0.2
  flutter_local_notifications: ^3.0.1
  flutter_native_timezone: ^1.0.4
  flutter_polyline_points:
  geolocator: ^6.1.1
  geocoding: ^1.0.5
  google_fonts: ^1.1.1
  google_maps_flutter: 
  http: ^0.12.2
  intl: ^0.16.1
  introduction_screen: ^1.0.9
  share: '>=0.6.5+4 <2.0.0'
  shared_preferences: '>=0.5.12+2 <2.0.0'
  sqflite: ^1.3.2+1
  timezone: ^0.5.9
  url_launcher: ^5.7.8
  weather: ^1.2.3
  web_scraper: ^0.0.6
  webfeed: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/schema.sql
    - assets/images/
    - assets/images/separator.png
    - assets/images/bandon-home-plan-your-visit-alt.jpg
    - assets/images/bandon-home-choose-your-table-green.jpg
    - assets/images/bandon-home-book-your-stay.jpg
    - assets/images/farm-to-table-apples.jpg
    - assets/images/separator-cranberry.png
    - assets/images/u-pick-paradise.jpg
    - assets/images/dining/bandon-fish-market.jpg
    - assets/images/dining/dessert.jpg
    - assets/images/dining/shrimp.jpg
    - assets/images/dining/all-dining.jpg
    - assets/images/dining/dining-restaurants.jpg
    - assets/images/dining/dining-specialty.jpg
    - assets/images/dining/dining-wine-beer.jpg
    - assets/images/things-to-do/bandon-things-to-do.jpg
    - assets/images/things-to-do/bandon-golfing.jpg
    - assets/images/things-to-do/bandon-hiking.jpg
    - assets/images/things-to-do/bandon-beaches.jpg
    - assets/images/things-to-do/bandon-fishing.jpg
    - assets/images/things-to-do/bandon-birding.jpg
    - assets/images/things-to-do/bandon-oldtown.jpg
    - assets/images/separator-golf.png
    - assets/images/separator-bicycle.png
    - assets/images/separator-beaches.png
    - assets/images/separator-suitcase.png
    - assets/images/plane-view.jpg 
    - assets/images/bandon-forest-generic.jpg
    - assets/images/bandon-mussels-generic.jpg
    - assets/images/bandon-sunset-generic.jpg
    - assets/images/bandon-seagull-generic.jpg
    - assets/images/maps/fly-portland.jpg
    - assets/images/maps/drive-portland.jpg
    - assets/images/lodging-wildspring-cabin.jpg
    - assets/images/drive-view.jpg
    # - assets/images/lighthouse.png
    # - assets/images/dining.png
    # - assets/images/map.png
    # - assets/images/bandon-logo.png
    # - assets/images/beach-sunset.jpg #tim-peterson-IIjWzuOaMdk-unsplash
    # - assets/
  # bandon-sunset-generic.jpg #Photo by Tim Peterson on Unsplash https://unsplash.com/photos/V5MQ6Moq-3w
  # drive-view.jpg #Photo by Cristofer Jeschke on Unsplash https://unsplash.com/photos/-fW7YPjhifk  
  # bandon-forest-generic.jpg #Photo by Dave Hoefler on Unsplash https://unsplash.com/photos/vA80ZTVyooc
  # plane-view.jpg #Photo by Ross Parmly on Unsplash https://unsplash.com/photos/rf6ywHVkrlY
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
